### ISSUE TITLE
Problem with volumes

### ISSUE THREAD

**Issue by dajoho** [tiangolo/babun-docker#1]
Hi! First of all, thank you for making this. I have been scouring the web for solutions, waiting for this bugfix to appear.. and it did! 

It almost all works as expected: I can start babun, then docker, then I get the tty error, then babun-docker springs to life and forwards the parameters to the docker binary.... BUT... I cannot mount any docker volumes with, for example, -v $(pwd)/src:/var/www/. The folders stay empty within the docker container.

Any ideas? I'm assuming it is a problem with winpty not understanding the paths. 

Dave

**Comment by tiangolo** [comment]
Hi Dave @dajoho

I'm glad it helped!

Yeah, I have some ideas about what is happening. Indeed, quite an amount of ideas. I think I know exactly what is happening.

Actually, you inspired me to write this Wiki entry, to explain and solve exactly that problem, I hope it helps:

https://github.com/tiangolo/babun-docker/wiki/Docker-Volumes-with-Babun

**Comment by dajoho** [comment]
Ooh! Thank you for that. That's a lot of information. I'll have a test through tomorrow and let you know how I get on!

**Comment by tiangolo** [comment]
@dajoho, I just automatized all the mounting of volumes. 

You can update **docker-babun** with `docker-babun-update`, then turn off your VirtualBox machine (if it is turned on) and use the commands as you would expect. They should "just work".

With this update all the drives in your Windows (and sub directories) are available to be used as volumes, not just those under `C:\Users` as with Docker Toolbox.

I would appreciate if you can test it and reply back with your results before closing this issue.

**Comment by tiangolo** [comment]
I will assume it is working now and close this issue.
