### ISSUE TITLE
Error during install. 

### ISSUE THREAD

**Issue by chrisdbarnett** [tiangolo/babun-docker#10]
If I run 
curl -s https://raw.githubusercontent.com/tiangolo/babun-docker/master/setup.sh | source /dev/stdin
In babun version 1.2.0, under Windows 10 Professional 

{ ~ }  » curl -s https://raw.githubusercontent.com/tiangolo/babun-docker/master/setup.sh | source /dev/stdin
**grep: '/home/chris/.babun-docker/setup.sh': No such file or directory**
{ ~ }  »

**Comment by tiangolo** [comment]
That's very strange @chrisdbarnett 

What the first line does is:
- download the setup file 
- immediately execute it in your terminal

What that setup file does is:
- clone this repo with git in your Babun Home directory (in `/home/chris/.babun-docker/`)
- add the needed variables (and the main function) to your babun startup (in `~/.zshrc`)

By what you tell me, it seems there's some error that prevents the repo to be cloned.

I can't guess what is happening apart from that, but you may help me. Can you try to follow the "manual installation" and see what happens? Please take note of each output and error.

Or if you want, the more precise way to debug it would be opening the setup.sh file in your browser and copying and running each line of it in your terminal to see what exactly doesn't work.

**Comment by chrisdbarnett** [comment]
Hi, thanks for getting back quickly. 

Same kinda thing with manual install:

{ ~ }  » **git clone https://github.com/tiangolo/babun-docker.git ./.babun-docker**
**Cloning into './.babun-docker'...**
**remote: Counting objects: 89, done.**
**remote: Total 89 (delta 0), reused 0 (delta 0), pack-reused 89**
**Unpacking objects: 100% (89/89), done.**
**Checking connectivity... done.**
{ ~ }  » **cd ./.babun-docker**
{ .babun-docker } master » **ls**
**bin  README.md  setup.sh**
{ .babun-docker } master » **source ./setup.sh**
**grep: '/home/chris/.babun-docker/setup.sh': No such file or directory**

Thanks,

Chris.

**Comment by chrisdbarnett** [comment]
This seems to be the crux of it:

{ .babun-docker } master » **grep $babun_docker_setup_str**
**grep: '/home/chris/.babun-docker/setup.sh': No such file or directory**

Opps...strike that....for now....

**Comment by chrisdbarnett** [comment]
OK...

echo $babun_docker_setup_str >> $HOME/.zshrc 

Just does the business....it did what it was supposed to....

The really strange thing...is that since I went and did that. 

{ .babun-docker } master » **source ./setup.sh**  
...now works! 

Bizarre. I'll run everything all over again under a different babun directory and see if I have the same problems.

**Comment by chrisdbarnett** [comment]
tiangolo,

I cannot reproduce on a clean install of babun...everything works fine and good on a clean babun install.

The install of babun I was originally using was not that old. It had a few things installed on it to do with Python and docker...mainly this:

http://blog.eisele.net/2015/06/docker-compose-on-windows-with-python.html

But even after running all of that on yet another clean install of baban I could not reproduce the original install error. 

Considering there wasn't much installed in the first place, I'm happy to start afresh as far as babun is concerned. 

Thanks,
Chris.

**Comment by tiangolo** [comment]
@chrisdbarnett Hmm, strange, maybe something in the old installation was changing the `$HOME` variable...

I'm glad you figured it out!

And thanks for reporting back, that way I know there's isn't a bug somewhere and I can close the issue.

Best!

**Comment by Morgy93** [comment]
I'm having the same issue.
Maybe I can try to dig into it somehow?
![babun](https://cloud.githubusercontent.com/assets/7961978/14088210/748eef52-f52e-11e5-8b29-9046c0d95193.PNG)

**Comment by Morgy93** [comment]
Okay this was a pretty easy one.
It was because of my bash shell.
While using zsh shell I don't get any error and it installs just fine.
One can change it pretty easy using:
`babun shell /bin/zsh`

**Comment by tiangolo** [comment]
I'm glad it's working now @Morgy93. 

It's strange that your default shell wasn't Zsh, Babun comes with it set as the default...

Anyway, I'm glad it's working now.

---

In case anyone in the future gets this same error, it might be related to the variable `$HOME`. It should point to your home directory, e.g. `/home/Thomas/`. 

It is normally set by default in any normal shell, but I guess some strange environment or something might break it.

To check the value of it you could run: `echo $HOME` and see what gets printed out.

**Comment by Morgy93** [comment]
@tiangolo That can't be related to the $HOME variable. It just doesn't work with bash at all. (Or maybe I made some strange changes to my bash?)
Try it for yourself one time.
`babun shell /bin/bash`
Restart Babun and try `source setup.sh`
With bash shell, the $HOME still points to `/home/Thomas`
Bash:
![bash](https://cloud.githubusercontent.com/assets/7961978/14098741/4f196fda-f57f-11e5-8f5b-5c8760fb7f2e.PNG)
Zsh:
![zsh](https://cloud.githubusercontent.com/assets/7961978/14098755/6cdb72b6-f57f-11e5-9cb4-17f0305bf456.PNG)

**Comment by tiangolo** [comment]
Thanks for the tip @Morgy93, that helped a lot.

I wrote a big fix that now allows using Bash. Actually, it even allows using Cygwin directly (although I still recommend Babun).

You can update with `babun-docker-update`.
