### ISSUE TITLE
Line wrapping does not move to new line

### ISSUE THREAD

**Issue by paritosh-gupta** [tiangolo/babun-docker#11]
Hi,
So I am having this issue on windows 7. If I docker exec -it or run a container and enter a long command the line-wraps somewhere in the middle of the terminal and instead of moving to the next line overwrites the existing line. Any ideas?

**Comment by tiangolo** [comment]
It has to do with the way Winpty works and the way it emulates a Windows console in the backend. 

Although it looks ugly and makes it hard to see what you are typing, the lines should execute as expected (as typed).

There's no easy way to fix it as it's a problem with the cmd Windows console and the way Winpty uses it, I'm sorry.

**Comment by paritosh-gupta** [comment]
Ah I see. Thanks for the reply! Closing the issue.
