### ISSUE TITLE
Add persistent mount support

### ISSUE THREAD

**Issue by olegweb** [tiangolo/babun-docker#12]
Can you:
1. Add some $babun_docker_persistent_volumes="c d" and insert mount command into /mnt/sda1/var/lib/boot2docker/profile
2. Fix mount command to: sudo mount -t vboxsf -o \"defaults,uid=`id -u docker`,gid=`id -g docker`,iocharset=utf8,rw\"

**Comment by olegweb** [comment]
Also add correct virtualbox path detection:
    VB_REG_KEY="HKEY_LOCAL_MACHINE\SOFTWARE\Oracle\VirtualBox"
    VB_REG_VALUE="InstallDir"
    REG=reg
    VB_PATH=$($REG query $VB_REG_KEY /v $VB_REG_VALUE | sed '/^$/d' | tail -n 1 | awk -F'[[:space:]][[:space:]][[:space:]]*' '{print $4}')

**Comment by tiangolo** [comment]
Thanks for the suggestions @olegweb !
1. I added functionality to use a config file where you can use a variable `babun_docker_volumes` for that specific purpose. I don't want to modify the `/mnt/sda1/var/lib/boot2docker/profile` file as I don't want to mess with boot2docker, in case that could break any future update of the VM or something similar. But the scripts and config were updated to use that volumes variable and configure it automatically. Please check the README (the main page) to see how it works (in the Configurations section).
2. Thanks for the hint on the mounting of volumes. I used it and adapted it to work with the rest of the program.

You can update by running `babun-docker-update`.

For the second comment, it seems very interesting. I'll check it later (hopefully tomorrow).

**Comment by olegweb** [comment]
Thanks tiangolo !

**Comment by tiangolo** [comment]
@olegweb, BTW, I checked the second comment, but the `reg` tool didn't work properly from Babun. Then I tried with Cygwin's `regtool`, but it didn't work consistently. It worked for some keys but not for others. 

So I resorted to having the VirtualBox `VBoxManage` path in a variable, in case you need to modify it, you can check the newest documentation (in the end of the README in the main GitHub page).
