### ISSUE TITLE
Bug with Docker Toolbox 1.11.0

### ISSUE THREAD

**Issue by olegweb** [tiangolo/babun-docker#14]
The wrapper function doesn't start docker.

**Comment by tiangolo** [comment]
@olegweb what error are you getting? 
Are you using the latest version? (update with `babun-docker-update`)
What is your OS? Windows 7? Windows 10?
Is the normal Quickstart Terminal working (without babun-docker)?

**Comment by olegweb** [comment]
Latest babun-docker, Win 8.1, Docker version 1.11.0  build 4dc5990
Quickstart Terminal working.
All works fine before i update to latest docker toolbox.
I think docker chaged some error messages and wrapper function doesn't detect it... so it doesn't start docker.

**Comment by tiangolo** [comment]
@olegweb That's strange, I just updated to Docker Toolbox 1.11.0 and everything is working as expected...

After the upgrade to Docker Toolbox 1.10 some errors changed and there was a fix for that (see https://github.com/tiangolo/babun-docker#2016-03-16), that's what made me think that you could be having an old **babun-docker** version...

Could you copy your terminal output here?

**Comment by olegweb** [comment]
{ ~ }  » docker-machine status                                                                  ~
Stopped
{ ~ }  » docker ps                                                                              ~
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.23/containers/json: open //./pipe/docker_engine: The system cannot find the file specified.
{ ~ }  » cd ~/.babun-docker
{ .babun-docker } master » git show --oneline -s
5529b6b Add VirtualBox path config to README.md

**Comment by tiangolo** [comment]
Thanks @olegweb !

I was actually able to reproduce the bug (I don't know why it wasn't happening before).

Can you update (`babun-docker-update`) and check if it's working for you now?

**Comment by olegweb** [comment]
Thanks tiangolo, it works :)

**Comment by tiangolo** [comment]
Great! Thanks for reporting back @olegweb
