### ISSUE TITLE
Could not read CA certificate

### ISSUE THREAD

**Issue by kelchm** [tiangolo/babun-docker#19]
I have the latest version of babun, babun-docker and Docker Toolbox for Windows installed.

The Docker Quickstart Terminal works as expected, when running a command such as `docker run hello-world`.  When trying to run the same command in Babun, I reveieve the following message: `Could not read CA certificate "C:\ca.pem": open C:%`

Any thoughts on what the issue might be here?

**Comment by tiangolo** [comment]
I'm not sure, that's strange... what else it says? Isn't there a message to re-create the certificates? Something like: `docker-machine regenerate-certs default`.

You may try that to see if it works.

**Comment by tiangolo** [comment]
@kelchm: A colleague had the same problem and I was able to debug it with his help. (It was a kind of corner case).

It should be working in the latest commit ae1b21b

Please run `babun-docker-update` and tell me if it's working now.

**Comment by kelchm** [comment]
@tiangolo, thanks for digging into that.  It actually mysteriously started working on it's own without me updating babun or anything else. I'll let you know if the issue reappears!
