### ISSUE TITLE
Setup does not work when spaces are in PATH

### ISSUE THREAD

**Issue by domkun** [tiangolo/babun-docker#20]
`/home/kun/.babun-docker/setup.sh:export:51: not valid in this context: Files/ConEmu:/cygdrive/c/Program`

needed to manually put quotes around statement like:
`export PATH="$PATH:$babun_docker_winpty_dir"`

**Comment by tiangolo** [comment]
Thanks for reporting @domkun, it should work now (commit f4f113f).

You can update with `babun-docker-update`.
