### ISSUE TITLE
Problems under bash

### ISSUE THREAD

**Issue by kenchilada** [tiangolo/babun-docker#27]
Cool project!

I use bash (unwilling to change).  I followed the setup instructions, did curl and update.  I had two issues...

First, the winpty binaries were never found by the shell even though the path you set looks correct.  Very strange.  I copied the winpty*.exe and winpty.dll to my `~/bin` folder and then things worked.  

Second, every time I run something that invokes babun-docker, I get this...

```
$ docker exec -it mycontainer ps
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
rm: remove regular file ‘/tmp/babun-docker-env-vars’? y
-- babun-docker: Using winpty
  PID TTY          TIME CMD
   70 ?        00:00:00 ps
```

It always prompts me to delete that "babun-docker-env-vars".  I changed "babun-docker.sh" around line 70 to use `rm -f` when it deletes this file to avoid the prompt.

Hope this is helpful!

**Comment by tiangolo** [comment]
Thanks for reporting it @kenchilada ! I just included your suggestion.
