### ISSUE TITLE
strange issue using winpty

### ISSUE THREAD

**Issue by xinity** [tiangolo/babun-docker#3]
hi,

from time to time i have this strange error message coming up :(

![winpty](https://cloud.githubusercontent.com/assets/1799009/10812861/974da802-7e1a-11e5-99b6-98c2ce59da8b.png)

any ideas where and why ?

Thanks for this great tweak by the way

**Comment by tiangolo** [comment]
Hi @xinity ! 

I'm glad it helped you :smile:

I've had that same issue some times, but not many. I think it's related to the way docker communicates with Windows consoles, maybe it's specially related to the combination of docker and winpty, as there's a StdStreams in the error (I guess it refers to stdin, stdout and stderr).

Normally, I just close and open Babun and it works again.

I'm not sure when that issue happens, if it is being a burden to you, you may help me trying to  discover what triggers it (or how to trigger and reproduce the issue), to narrow the problem: maybe it's after a sleep / wake Windows cycle, or after an interactive session when the VM was started by the Quickstart Terminal and not the script, etc...

**Comment by xinity** [comment]
i'll try and figure out what's going wrong, if i can PR i'll do :)

**Comment by tiangolo** [comment]
Great, thanks @xinity !

**Comment by xinity** [comment]
error happening again, is there any chances we can put a little debug to see what's going on wrong ?

**Comment by tiangolo** [comment]
You could use `$docker_bin`, that variable holds the original `docker`, you could try the command you are using with that variable, maybe prepending `console` to use winpty.

For example:

```
console $docker_bin exec -it mycontainer bash
```

If the error persists, it would be related to Docker or Winpty and not to Docker-Babun, so we probably wouldn't have an easy way to solve it without fixing the code for those other projects.

Also, you may try to run the command with the original Quickstart Terminal, to see if the error happens there too.

**Comment by tiangolo** [comment]
I think this issue is related to https://github.com/docker/docker/issues/17430 and https://github.com/docker/docker/issues/12506

**Comment by xinity** [comment]
yup i saw

https://github.com/docker/docker/issues/12506 is ongoing :( 
damn it !

**Comment by tiangolo** [comment]
Well, as it seems this issue is more related to Docker itself, I will close it here.
