### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by Blaiserman** [tiangolo/babun-docker#30]
Where is the uninstall script for babun-docker? I used docker toolbox but i will install docker for windows so I need to un install babun-docker.

**Comment by tiangolo** [comment]
**babun-docker** only works inside Babun, so if you are using Docker for Windows you are probably going to use PowerShell that is what they support (as far as I know).

If you still want to remove **babun-docker** from you Babun, refer to: https://github.com/tiangolo/babun-docker/issues/29

**Comment by tiangolo** [comment]
Since there were no more comments, I'll assume you solved your problem. I'll close this issue.
