### ISSUE TITLE
Unable to communicate with docker when proxy set

### ISSUE THREAD

**Issue by woyczek** [tiangolo/babun-docker#33]
When http_proxy is set:
✓ (0) ~ $ docker ps  
+ docker ps  
+ [[ -z x ]]  
+ [[ -z x ]]  
+ IFS=  
+ babun_docker_use_winpty=0  
+ babun_docker_run_again=0  
+ '/cygdrive/c/Program Files/Docker Toolbox/docker' ps  
+ read -r line  
+ echo 'error during connect: Get https://192.168.99.100:2376/v1.36/containers/json: Gateway Timeout'  

The solution is to unset http_proxy before communicate with docker container.

```
diff --git a/bin/babun-docker.sh b/bin/babun-docker.sh
index 0efee21..01e8f0b 100644
--- a/bin/babun-docker.sh
+++ b/bin/babun-docker.sh
@@ -5,6 +5,9 @@ if [[ -z "$docker_bin" ]] ; then
   docker_bin=$(which docker) ;
 fi
 function docker {
+  # Remove proxy
+  PX=$http_proxy
+  unset http_proxy
   if [[ -z ${babun_docker_old_IFS+x} ]] ; then
     babun_docker_old_IFS=$IFS
   fi
@@ -79,4 +82,6 @@ function docker {
    docker $@
  fi
  IFS=$babun_docker_old_IFS
+  http_proxy=$PX
+  export http_proxy
 }
```

**Comment by tiangolo** [comment]
Thanks for the report, I'll check it soon.

**Comment by tiangolo** [comment]
I'm trying to check it, but I don't see when or how would `http_proxy` get set. So, I'm not being able to cause the problem that this would solve.

Do you have a way to reproduce the problem?

**Comment by tiangolo** [comment]
As this issue is quite old, I'll close it now. But feel free to add more comments, re-open it or create new ones.
