### ISSUE TITLE
docker-machine on babun gets different results than docker quickstart/cmd

### ISSUE THREAD

**Issue by rohitsodhia** [tiangolo/babun-docker#35]
When I first installed babun-docker, running `docker-machine ls/start/stop` behaved the same as the docker quickstart terminal. However, I upgraded docker toolbox (and virtualbox through the installer), and now when I try starting or stopping my default machine, if a docker-machine isn't already started, it starts one, but virtualbox shows the default box still offline. If one was started in the quickstart terminal, it goes through some work and then just says 'Machine "default" is already started/stopped.", and a `docker-machine ps` shows the state as `Timeout`. Starting a new machine goes through the process, I see all the commands of a machine starting, but no new machine starts up in the virtualbox interface. And if I start it in babun first, I can't start anything in quickstart terminal.

This is really frustrating, as it means I can't figure out what's starting my docker machines or where they live, or what settings are running. For now, I'm going to stop using docker with babun, which is frustrating, because it was great being able to use docker with babun.

**Comment by tiangolo** [comment]
Sorry for the delay, I've been busy building https://github.com/tiangolo/fastapi and other tools.

babun-docker (this project) doesn't change anything about `docker-machine`. It uses it directly.

It only replaces the command `docker` when running on Babun. And what it does is make sure that the Docker Machine "default" is started if it's not, using the same `docker-machine` command (but without modifying it). And then, when a command that needs an interactive session, like a `docker exec` is called, it detects the error about needing a TTY session, and calls it again with `winpty`, a program to convert the communication and allow having an interactive session in Babun.

If you try those same steps, without babun-docker, running `docker-machine ls/start/stop`, does it work as expected? Even after the upgrade?

Also, check out the configurations: https://github.com/tiangolo/babun-docker#configurations

If you need to use a Docker Machine different than "default", you can put that in the settings.
