### ISSUE TITLE
docker exec not working with Docker for Windows Desktop

### ISSUE THREAD

**Issue by mckinnsb** [tiangolo/babun-docker#36]
Hi,

I tried installing babun-docker to use docker w/ babun. Whenever I use docker commands, I get:

```
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
-- babun-docker: Using winpty
```

It also seems that the "console" alias is not set. It would be nice to use babun w/ docker but I'm about ready to give up. I've tried running babun-docker-update and updating babun itself but nothing seems to work.

**Comment by tiangolo** [comment]
Sorry for the delay, babun-docker works only with Docker Toolbox.

If you are using Docker for Windows I think you have to use PowerShell, or maybe Git Bash might work.

**Comment by mckinnsb** [comment]
Thanks for the reply.

It's a bit of a shame because it seems that Docker Toolbox is not being
worked on as actively/will probably be deprecated at some point, and this
was really the only thing stopping me from using Babun. Oh well.

**Comment by tiangolo** [comment]
Yep, I agree, it's a shame :disappointed:.

But yes, if you are able to (if you have Windows 10 pro version), you would probably be better off with official Docker for Windows.
