### ISSUE TITLE
Winpty not work

### ISSUE THREAD

**Issue by Brialius** [tiangolo/babun-docker#5]
Cant see anything in console (
Commands are running, but not displayed.
![image](https://cloud.githubusercontent.com/assets/6441812/12086476/aeca72da-b2db-11e5-8e14-9e341d6ab5a5.png)
![image](https://cloud.githubusercontent.com/assets/6441812/12086479/b611b60c-b2db-11e5-96ea-fe20d19fa462.png)

**Comment by tiangolo** [comment]
You are probably using an old version of babun-docker, try running:

```
babun-docker-update
```

If you don't seem to have that command then you have a version even older, you can then just follow the instructions to install again.

**Comment by Brialius** [comment]
![image](https://cloud.githubusercontent.com/assets/6441812/12142139/bc577d60-b486-11e5-9ae5-27158b59ca30.png)
i checked updates..

**Comment by tiangolo** [comment]
Hmmm, that's strange... please, try a common image (Debian) to see if it is related to the jenkins image directly:

```
docker run -d --name mydebian debian ping google.com
docker exec -it mydebian bash
```

Let's see what that outputs...

If it works normally, the problem would be related to that specific jenkins image.

**Comment by Brialius** [comment]
![image](https://cloud.githubusercontent.com/assets/6441812/12228599/ebb51434-b84e-11e5-8669-a7dd677f30fd.png)

**Comment by tiangolo** [comment]
Hmm, that's really weird... It works for me normally...

So, your problem is not related to Jenkins.

But as it works in my system and not in yours it must be related to something specific in your environment. Let's see if it's related to Winpty, Babun or Docker (we already saw it doesn't seem related to the image).

Please, first, try running the same commands in the Docker Quickstart Terminal, to see if it's related to the Docker installation. If I'm not wrong, in that terminal you have to prepend the "winpty" command, as in:

```
docker run -d --name mydebian debian ping google.com
winpty docker exec -it mydebian bash
```

If it works in the Quickstart Terminal but not in Babun, we know the problem is probably not related to Docker.

Then try to use winpty in Babun. The command for "winpty" in Babun is "console" (instead of "winpty"), try running:

```
console ping google.com
```

And let's see what those two things output.

**Comment by Brialius** [comment]
from docker quickstart:
![image](https://cloud.githubusercontent.com/assets/6441812/12231117/3ca0d894-b866-11e5-8a0c-3f5b496c7e6a.png)
![image](https://cloud.githubusercontent.com/assets/6441812/12231124/4c0ef644-b866-11e5-849f-0696119d8024.png)

from Babun:
![image](https://cloud.githubusercontent.com/assets/6441812/12231147/5f86cfa8-b866-11e5-974c-ff9de2492c68.png)

**Comment by tiangolo** [comment]
Ah! That seems to narrow the problem. 

It seems your winpty is broken. It might be that it got corrupted while downloading.

Please, try reinstalling winpty with:

```
rm -rf ~/.winpty
```

And install again by running the babun-docker installation (it will re-install winpty):

```
curl -s https://raw.githubusercontent.com/tiangolo/babun-docker/master/setup.sh | source /dev/stdin
```

Also, try restarting your Windows. Windows is weird and does weird stuff, many things get magically solved by just restarting it.

**Comment by Brialius** [comment]
Thank you, but it didn't help :(

**Comment by tiangolo** [comment]
Did you restart Windows?

Did you remove and re-install winpty?

**Comment by Brialius** [comment]
Did you restart Windows?
Yes

Did you remove and re-install winpty?
Yes

**Comment by tiangolo** [comment]
Hmm, that's very strange, I'm not sure if it actually is related to winpty. You may try uninstalling and reinstalling Babun, and if that doesn't work, try uninstalling and reinstalling Docker Toolbox. Although it doesn't seem related to Docker Toolbox... so try the others first.

**Comment by Brialius** [comment]
I'm reinstall Babun and update cigwin in it, then reinstall docker kitematic.
Unfortunately it not help. Problem still present..

**Comment by tiangolo** [comment]
I'm sorry, but I can't seem to reproduce your error and I can't re-create your environment to help you solve it... 

Maybe you could try in a friend's computer to compare the environments, or you may try manually installing winpty, to try to find what is making it misbehave.

**Comment by uocnb** [comment]
Look like problem come with Windows 10 and babun.
I can use Mintty with original cygwin and latest winpty.

**Comment by tiangolo** [comment]
@tiger2wander: And were you having the same problem as @Brialius?

**Comment by Brialius** [comment]
on my work comp with Windows 7 with latest updates - winpty not work
on my home comp with Win 7 sp1 without any updates - all works fine

work comp in domain and i can't rollback some updates..
and i don't want  update my home comp, sorry..

**Comment by tiangolo** [comment]
Then it seems it's a problem with your work comp installation @Brialius, try downloading a Winpty cygwin release from the source repo: https://github.com/rprichard/winpty/releases.

Download it somewhere and use it directly (from Babun) to see if it works.

**Comment by Brialius** [comment]
Great news: it works for me with winpty-0.2.1-cygwin-2.3.0-ia32.tar.gz
Thank you!

**Comment by uocnb** [comment]
:+1:  yes, it's work with latest 32 bit version.

Another issue is docker function not wrap wimpty to run docker:

```
~$ docker run -it ubuntubash
cannot enable tty mode on non tty input
```

Work well with manual wrap

```
~$ console docker run -it ubuntubash
root@804b0c14a30c:/#
```

**Comment by tiangolo** [comment]
Excellent @Brialius!

@tiger2wander that's strange, maybe you need to restart Babun, because that message is exactly what would trigger docker-babun to use Winpty.

If it doesn't work, try running:

```
which docker
```

And 

```
echo $docker_bin
```

And tell me what those two output.

**Comment by tiangolo** [comment]
I just updated **babun-docker** and it installs (or updates) to the latest winpty. That should fix your problems.

(You can update to the latest version running `babun-docker-update`)

If you still have problems please comment here and I'll re-open this issue.

**Comment by GodGinrai** [comment]
winpty 2.2 broke it for me.  When I switched back to winpty 2.1 again, it fixed it.

**Comment by tiangolo** [comment]
@GodGinrai specifically what or how did it broke it? Can you paste your log / console?

**Comment by GodGinrai** [comment]
Specifically, `console <somecommand>` wouldn't even return output no matter what I threw at it.  When I switched to 2.1, it all worked as it should.

**Comment by tiangolo** [comment]
That's very strange, it works form me @GodGinrai. But I'm glad you were able to solve it.

**Comment by yclian** [comment]
@tiangolo Check my last PR, it should fix the strange `winpty` not found in path issue.
